### ISSUE TITLE
Storybook/React/Twig: Add canonical urls

### ISSUE THREAD

**Issue by johnpauldavis** [international-labour-organization/designsystem#246] opened 2022-12-01 15:31 UTC
The canonical urls for the Storybook projects are:

https://react.ui.ilo.org/

https://twig.ui.ilo.org/

Add canonical url tags to each storybook project.

E.g. `<link rel="canonical" href="https://react.ui.ilo.org">`

2. Set the homepage properties to the package.json files of the react and twig package, so they’ll appear in npm

**Comment by justintemps** [comment] 2023-03-01 08:37
Closing as a duplicate of #168

**Closed by justintemps** 2023-03-01 08:37 UTC
