### ISSUE TITLE
Bug graphic card: triangle in the right top corner flickers

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#342] opened 2023-05-23 12:25 UTC
The triangle flickers when we hover the card. See here:

https://www.awesomescreenshot.com/video/17656784?key=e70e6e6474ed3ab3bb9056d8f7644875

**Comment by justintemps** [comment] 2023-05-25 13:18
This is a duplicate of #257

**Closed by justintemps** 2023-05-25 13:18 UTC
Labels: 2023:1
